# -*- coding: utf-8 -*-
"""birthday_paradox.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xe9hNtSYlVq0LvPDLihffsCJVgowS8eW
"""

import numpy as np
import matplotlib.pyplot as plt

def has_duplicate(birthdays):
    return len(birthdays) != len(set(birthdays))

def simulate_birthday_problem(n, simulations=10000):
    duplicate_counts = []
    for _ in range(simulations):
        birthdays = np.random.randint(1, 366, size=n)
        duplicate_counts.append(has_duplicate(birthdays))
    return np.mean(duplicate_counts)

# Number of classmates to simulate
max_classmates = 50
simulations = 10000
probabilities = []

# Simulate for different numbers of classmates
for n in range(1, max_classmates + 1):
    prob = simulate_birthday_problem(n, simulations)
    probabilities.append(prob)

# Plot the results
plt.figure(figsize=(10, 6))
plt.plot(range(1, max_classmates + 1), probabilities, marker='o')
plt.xlabel('Number of Classmates (n)')
plt.ylabel('Probability of a Shared Birthday')
plt.title('Probability of Shared Birthday vs. Number of Classmates')
plt.grid(True)
plt.show()